# Generated by Django 5.1.3 on 2024-12-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0018_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
