# Generated by Django 5.1.3 on 2025-02-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0019_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
