# Generated by Django 5.1.3 on 2025-02-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0021_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='lon',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
